### ISSUE TITLE
gomail.v2 is unmaintained

### ISSUE THREAD

**Issue by cryptix** [qor/mailer#3]
I think the imports should be moved to `github.com/go-mail/mail`.

See go-gomail/gomail#104.

**Comment by cryptix** [comment]
This was fixed in  0555e49

**Comment by Neustradamus** [comment]
@cryptix: It is possible to change it?
- https://github.com/go-mail/mail

It has been unmaintained and maybe vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/qor/mailer/issues/4
